<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("NumPy stands for Numerical Python")

NumPy stands for Numerical Python


Uses of NumPy
* **ndarray:** An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Mathematical functions** for fast operations on entire arrays of data without having to write loops.
* **Tools** for reading/writing array data to disk and working with memory-mapped files.
* **Linear algebra**, random number generation, and Fourier transform capabilities.
* **A C API** for connecting NumPy with libraries written in C, C++, or FORTRAN.

In [2]:
print("NumPy array are typically faster when compared to loops in python")

NumPy array are typically faster when compared to loops in python


In [3]:
import numpy as np

In [4]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [5]:
%timeit my_arr2 = my_arr*2

1.25 ms ± 315 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit my_list_2 = [x*2 for x in my_list]

121 ms ± 57.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## NumPy ndarray

### Initialization and Data Types

In [7]:
data = np.array([[1.5 , -0.1 , 3] , [0 , -3 , 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data*10
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [9]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [1 , 2 , 3 , 4]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4])

In [13]:
data2 = [[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('int64')

In [17]:
arr2.dtype

dtype('int64')

In [18]:
print("Unless explicitly specified numpy.array tries to infer a good data type for the array that it creates")

Unless explicitly specified numpy.array tries to infer a good data type for the array that it creates


In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((2 , 5) , "float")

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((1 , 5) , "int64")

array([[1, 1, 1, 1, 1]])

In [22]:
np.empty((2 , 3 , 2))

array([[[3.72177030e-315, 0.00000000e+000],
        [2.10077583e-312, 6.79038654e-313],
        [2.22809558e-312, 2.14321575e-312]],

       [[2.35541533e-312, 6.79038654e-313],
        [2.22809558e-312, 2.14321575e-312],
        [2.46151512e-312, 2.41907520e-312]]])

In [23]:
print("While initializing a empty array we have to keep in mind that we have to poplulate the whole array")

While initializing a empty array we have to keep in mind that we have to poplulate the whole array


In [24]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
np.full((2 , 2) , 67)

array([[67, 67],
       [67, 67]])

In [27]:
np.identity(5 , "int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
arr = np.array([1 , 2 , 3 , 4 , 5])
arr.dtype

dtype('int64')

In [29]:
arr2 = arr.astype("float")
arr2.dtype

dtype('float64')

In [30]:
arr2

array([1., 2., 3., 4., 5.])

In [31]:
arr = np.array([3.7,-1.2,-2.6, 0.5, 12.9, 10.1])
arr.astype("int8")

array([ 3, -1, -2,  0, 12, 10], dtype=int8)

In [32]:
num_string = np.array(["1" , "2" , "3"])
num_string.astype("float")

array([1., 2., 3.])

In [33]:
print("We can also refer to another array datatype in dtype argument")

We can also refer to another array datatype in dtype argument


In [34]:
int_arr = np.array([1 , 2 , 3 , 4])
float_arr = np.array([1.2 , 3.4 , 2.9])
float_arr.astype(int_arr.dtype)

array([1, 3, 2])

In [35]:
print("Calling astype always creates a new array even if the new dtype is the same as the old dtype.")

Calling astype always creates a new array even if the new dtype is the same as the old dtype.


### Arithmetic with NumPy Arrays

In [36]:
arr = np.array([[1 , 2 , 3] , [4 , 5 , 6]])

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [39]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [40]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [43]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [44]:
arr2 = np.array([[2 , 1 , 2] , [4 , 5 , 1]])
arr2

array([[2, 1, 2],
       [4, 5, 1]])

In [45]:
arr > arr2

array([[False,  True,  True],
       [False, False,  True]])

### Indexing and Slicing

#### Basic Slicing

In [46]:
arr = np.arange(10)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
print(arr[5])

5


In [49]:
arr[5:8]

array([5, 6, 7])

In [50]:
arr[5:8] = 1
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 8, 9])

In [51]:
arr_slice = arr[5:8]

In [52]:
arr_slice

array([1, 1, 1])

In [53]:
arr_slice[1] = 12345

In [54]:
arr

array([    0,     1,     2,     3,     4,     1, 12345,     1,     8,
           9])

In [55]:
print("We Can see the original array is changed when we changed the sliced array")

We Can see the original array is changed when we changed the sliced array


In [56]:
print("Hence the array is not copied and Directly reffered , This is done for memory limits")

Hence the array is not copied and Directly reffered , This is done for memory limits


In [57]:
print("For explicitly copying we need to do arr[5:8].copy")

For explicitly copying we need to do arr[5:8].copy


In [58]:
arr_slice[:] = 67         # For allotting whole array
arr

array([ 0,  1,  2,  3,  4, 67, 67, 67,  8,  9])

In [59]:
arr = np.array([[1,2,3] , [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr[1]

array([4, 5, 6])

In [61]:
print(arr[1][1])

5


In [62]:
arr3d = np.array([[[1,2,3],[4,5,6,]] , [[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3d.shape

(2, 2, 3)

In [64]:
arr3d.ndim

3

In [65]:
arr3d.size

12

In [66]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr3d[0] = 1    # Scalars can be assigned to array

In [68]:
arr3d

array([[[ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[1][0]

array([7, 8, 9])

In [70]:
print(arr3d[1][0][2])

9


In [71]:
arr = np.array([1,2,3,4,5,6,7])
arr[1:6]

array([2, 3, 4, 5, 6])

In [72]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr2d[:2 , 1:]

array([[2, 3],
       [5, 6]])

In [75]:
low_dim_arr = arr2d[1 , :2]
low_dim_arr

array([4, 5])

In [76]:
low_dim_arr.shape

(2,)

In [77]:
arr2d[:2,2]

array([3, 6])

In [78]:
print(arr2d[:,2:3])       # Returns a matrix of 3*1
print(f"Shape - {arr2d[:,2:3].shape}")

[[3]
 [6]
 [9]]
Shape - (3, 1)


In [79]:
print(arr2d[:,2])       # Returns a 1D list
print(f"Shape - {arr2d[:,2].shape}")

[3 6 9]
Shape - (3,)


In [80]:
arr2d[:2 , 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### Boolean Indexing

In [81]:
names = np.array(["Bob" , "Joe" , "Will" , "Bob" , "Will" , "Joe" , "Joe"])
data = np.array([[1,2] , [-1,4] , [-3, 5] , [6 ,7] , [7 ,8] , [8 ,9] , [10 , 11]])

In [82]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [83]:
data

array([[ 1,  2],
       [-1,  4],
       [-3,  5],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [10, 11]])

In [84]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [85]:
data[names == "Bob"]

array([[1, 2],
       [6, 7]])

In [86]:
data[names == "Bob" , 1:]

array([[2],
       [7]])

In [87]:
data[names == "Bob" , 1]

array([2, 7])

In [88]:
print("Boolean array must be same length as the array axis it is indexing")

Boolean array must be same length as the array axis it is indexing


In [89]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [90]:
data[~(names == "Bob")]

array([[-1,  4],
       [-3,  5],
       [ 7,  8],
       [ 8,  9],
       [10, 11]])

In [91]:
data[names != "Bob"]

array([[-1,  4],
       [-3,  5],
       [ 7,  8],
       [ 8,  9],
       [10, 11]])

In [92]:
mask = (names == "Bob") | (names == "Will")
data[mask]

array([[ 1,  2],
       [-3,  5],
       [ 6,  7],
       [ 7,  8]])

In [93]:
mask

array([ True, False,  True,  True,  True, False, False])

In [94]:
data[mask]

array([[ 1,  2],
       [-3,  5],
       [ 6,  7],
       [ 7,  8]])

In [95]:
print("Selecting data from an array by Boolean indexing and assigning the result to a new variable always create a copy of the data")

Selecting data from an array by Boolean indexing and assigning the result to a new variable always create a copy of the data


In [96]:
print("In Case of NumPy We can only use (| and &) not (or and and)")

In Case of NumPy We can only use (| and &) not (or and and)


In [97]:
data[data<0] = 0
data

array([[ 1,  2],
       [ 0,  4],
       [ 0,  5],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [10, 11]])

In [98]:
data[names != "Joe"] = 7
data

array([[ 7,  7],
       [ 0,  4],
       [ 7,  7],
       [ 7,  7],
       [ 7,  7],
       [ 8,  9],
       [10, 11]])

#### Fancy Indexing

In [99]:
arr = np.zeros((8,4))

In [100]:
for i in range(8):
  arr[i] = i

In [101]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [102]:
arr[[4 , 3 , 5 , 7]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])

In [103]:
print("To select a subset of rows in particular order")

To select a subset of rows in particular order


In [104]:
arr[[-3,-2,-1,0]]

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.]])

In [105]:
arr = np.arange(40).reshape((8,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [106]:
arr[[1,2,3,4],[1,2,3,4]]

array([ 6, 12, 18, 24])

In [107]:
arr[[1,5,7,2]][:,[0,3,1,2]]           # Quite Fancy

array([[ 5,  8,  6,  7],
       [25, 28, 26, 27],
       [35, 38, 36, 37],
       [10, 13, 11, 12]])

In [108]:
arr[[1,2,3,4],[1,2,3,4]] = 0
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [109]:
print("Fancy Indexing & Boolean Indexing make copies of the matrix rather than returning a view")

Fancy Indexing & Boolean Indexing make copies of the matrix rather than returning a view


#### Transposing Arrays and Swapping Axes

In [110]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [111]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [112]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [113]:
arr@arr.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [114]:
print("Simple .T is a special Case of Swapping Axes")

Simple .T is a special Case of Swapping Axes


In [115]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [116]:
arr.swapaxes(0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [117]:
print("Both transposing and swapping axes returns a view of the array")

Both transposing and swapping axes returns a view of the array


In [118]:
print("Slicing , Transposing , Swapping - View")
print("Fancy Indexing , Boolean Indexing - Copy")

Slicing , Transposing , Swapping - View
Fancy Indexing , Boolean Indexing - Copy
